#!/usr/bin/env node
const program = require('commander')

program
.option('-s, --someflag', 'some boolean flag')
.parse(process.argv)

console.log('from yo-foo')
console.log('program.args', program.args)
console.log('program.someflag', program.someflag)
